"""Pressure category column added to data table

Revision ID: 49bc7cbbcc4d
Revises: a78ecd777649
Create Date: 2019-11-09 11:57:40.076000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bc7cbbcc4d'
down_revision = 'a78ecd777649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('pressure_category', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'pressure_category')
    # ### end Alembic commands ###
