"""User id columns to data table

Revision ID: a78ecd777649
Revises:
Create Date: 2019-11-08 16:53:07.802272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78ecd777649'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('created', sa.DateTime(), nullable=False))
    op.alter_column('data',
                    'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True
                    )
    op.create_index(op.f('ix_data_user_id'), 'data', ['user_id'], unique=False)
    op.create_foreign_key(None,
                          'data',
                          'users',
                          ['user_id'],
                          ['id'],
                          ondelete='CASCADE'
                          )
    op.drop_column('data', 'date')
    op.drop_column('data', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('time',
                                    sa.TEXT(),
                                    autoincrement=False,
                                    nullable=False
                                    ))
    op.add_column('data', sa.Column('date',
                                    sa.TEXT(),
                                    autoincrement=False,
                                    nullable=False
                                    ))
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_index(op.f('ix_data_user_id'), table_name='data')
    op.alter_column('data',
                    'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False
                    )
    op.drop_column('data', 'created')
    # ### end Alembic commands ###
